Inter list
rotshidzw/to-do-list pull request #3
Opened 2022-05-12 17:09 UTC by rotshidzw

- Add a new JavaScript file and import it as a module:
- it will contain methods related to the status updates (completed: true / false).
- Add event listener to the checkbox (change).
- Update items object's value for completed key upon user actions.
- Implement a function for the "Clear all completed" button (use filter() method).
- Store the updated array of items in local storage, so the user gets the correct list values after the page reloads.

2022-05-12 20:25 UTC, Gambit142 requested changes
Hi @rotshidzw 👋, 

Good job so far!

## Highlights
- All linters checks passed 💯 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- I noticed that when I tried to run `npm run start`, I got some errors. The error is a result of putting the `src` as a subfolder to the `modules` folder instead of the other way around. Remember that in your webpack.config.js file, you indicated entry as `'./src/index.js'` and not `'./modules/src/index.js'`. Kindly fix this error. 
 
- _Kindly check the comments under the review for other required changes._ 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- You can also consider the optional suggestion I made under the review. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-12 20:25 UTC, Gambit142 commented on modules/src/index.js
> +    });
- [ ] (Required) When I change the `Completed` status of a task and I reload the page, the status update is lost. Although the data is stored in the `localStorage,` there is no function or line of code to fetch data from the `localStorage`. I would like to advise you to always check if there is data in the localStorage upon reload of the webpage. If there is data stored in there, you can retrieve it and assign the `list` array to the data retrieved.  If there is none stored, you can set the `list` array to an empty array.

2022-05-12 20:25 UTC, Gambit142 commented on modules/src/index.js
> +});
- [ ] (Required) When I delete all  _**completed tasks**_ and I reload the page, the data is not retrieved from the `localStorage`. Although the data is stored in the `localStorage,` there is no function or line of code to fetch data from the `localStorage`. I would like to advise you to always check if there is data in the localStorage upon reload of the webpage. If there is data stored in there, you can retrieve it and assign the `list` array to the data retrieved.  If there is none stored, you can set the `list` array to an empty array.

2022-05-13 10:44 UTC, codepantha approved these changes
Hi @rotshidzw 👋,

## STATUS: APPROVED ✔️  

Well done implementing all the required changes 👍 👏 
Your project is complete now complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

### Highlights 🎯 
✔️ Descriptive PR
✔️ Meaningful commit messages
✔️ Linter checks

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-13 10:46 UTC, merged

2022-07-07 19:10 UTC, AmaduKamara reviewed
# Status: Approved 🟢🟢🟢 

Hi @rotshidzw,

![YesYouAreGIF (4)](https://user-images.githubusercontent.com/50941074/177853161-bb0c174e-f07d-4c96-8fa6-366d8b8569ad.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ Todo completed status change upon user interaction
✅ App design is cool 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-11 13:13 UTC, ogagaoghene reviewed
Nice work. Your work is complete.

2022-07-11 13:13 UTC, ogagaoghene commented on dist/index.html
> -
Everything is okay. Nice work. Your project is approved

2022-07-11 13:14 UTC, ogagaoghene reviewed
Your work is okay

2022-07-11 13:26 UTC, ogagaoghene reviewed
Nice work.Thumbs up.